In [1]:
import numpy as np 
import tensorflow as tf 
import torch

In [2]:
shape = (3,4)

In [4]:
arr_zeros = np.zeros(shape)
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
tensor_tf_zeros = tf.zeros(shape)
tensor_tf_zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [6]:
tensor_pt_zeros = torch.zeros(shape)
tensor_pt_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
arr_ones = np.ones(shape)
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
tensor_tf_ones = tf.ones(shape)
tensor_tf_ones

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [9]:
tensor_pt_ones = torch.ones(shape)
tensor_pt_ones 

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
value = 5 

In [11]:
arr_numbs = np.full(shape, value)
arr_numbs

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [15]:
pt_numbs = torch.full(shape, value)
pt_numbs

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])

In [14]:
tf_numbs = tf.fill(shape, value)
tf_numbs

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])>