# Lý thuyết

In [104]:
import numpy as np 

In [105]:
arr_1 = np.array([[1, 2], [3, 4]])
arr_1

array([[1, 2],
       [3, 4]])

In [106]:
arr_transposed_1 = np.transpose(arr_1)
arr_transposed_1

array([[1, 3],
       [2, 4]])

In [107]:
arr_transposed_2 = arr_1.T
arr_transposed_2

array([[1, 3],
       [2, 4]])

In [108]:
import torch 

In [109]:
tensor_1 = torch.tensor([[1, 2], [3, 4]])
tensor_1

tensor([[1, 2],
        [3, 4]])

In [110]:
tensor_tranposed_1 = torch.t(tensor_1)
tensor_tranposed_1

tensor([[1, 3],
        [2, 4]])

In [111]:
tensor_tranposed_2 = torch.transpose(tensor_1, 0, 1)
tensor_tranposed_2

tensor([[1, 3],
        [2, 4]])

In [112]:
import tensorflow as tf 

In [113]:
tensor_1 = tf.constant([[1, 2], [3, 4]])
tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [114]:
tensor_tranposed_1 = tf.transpose(tensor_1)
tensor_tranposed_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]])>

In [115]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
total_sum = np.sum(arr)
total_sum

21

In [117]:
column_sum = np.sum(arr, axis = 0)
column_sum

array([5, 7, 9])

In [118]:
row_sum = np.sum(arr, axis = 1)
row_sum

array([ 6, 15])

In [119]:
tensor_1 = torch.tensor([[1, 2], [3, 4]])
tensor_1

tensor([[1, 2],
        [3, 4]])

In [120]:
tensor_sum = torch.sum(tensor_1)
tensor_sum

tensor(10)

In [121]:
tensor_sum_axis_0 = torch.sum(tensor_1, axis = 0)
tensor_sum_axis_0

tensor([4, 6])

In [122]:
tensor_sum_axis_1 = torch.sum(tensor_1, axis = 1)
tensor_sum_axis_1

tensor([3, 7])

In [123]:
tensor_1 = tf.constant([[1, 2], [3, 4]])
tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [124]:
tensor_sum_axis_0 = tf.reduce_sum(tensor_1, axis = 0)
tensor_sum_axis_0

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6])>

In [125]:
tensor_sum_axis_1 = tf.reduce_sum(tensor_1, axis = 1)
tensor_sum_axis_1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 7])>

# Bài tập

In [126]:
np.random.seed(2024)

In [127]:
torch.manual_seed(2024)

In [128]:
tf.random.set_seed(2024)

In [129]:
np_arr_1 = np.random.randint(-10, 10, (3,4))
np_arr_1 

array([[ -2, -10, -10,  -6],
       [ -1,  -9,  -7,   0],
       [ -8, -10,  -5,   7]])

In [130]:
np_arr_2 = np.random.randint(-10, 10, (3,4))
np_arr_2 

array([[ 5,  0,  4,  5],
       [ 1, -3,  8, -1],
       [-4,  0, -9, -5]])

In [131]:
torch_tensor_1 = torch.randint(-10, 10, (3, 4))
torch_tensor_1

tensor([[  2,   0,  -6, -10],
        [ -7, -10,   0,   1],
        [  3,   9,   7,  -6]])

In [132]:
torch_tensor_2 = torch.randint(-10, 10, (3, 4))
torch_tensor_2

tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]])

In [133]:
tf_tensor_1 = tf.random.uniform(minval = -10, maxval = 10, shape = (3, 4))
tf_tensor_1

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 8.006859 , -6.109333 , -2.786193 ,  3.2723808],
       [ 5.321069 , -5.681262 ,  2.5234718, -8.523844 ],
       [-5.587461 ,  8.687361 ,  8.665581 ,  3.8534088]], dtype=float32)>

In [134]:
tf_tensor_2 = tf.random.uniform(minval = -10, maxval = 10, shape = (3, 4))
tf_tensor_2

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.6345768 ,  5.242193  ,  0.43196487, -4.9151683 ],
       [-3.8236713 , -0.25904465, -8.645498  , -3.7031531 ],
       [ 2.0925856 ,  5.5088787 ,  7.718027  , -7.3018003 ]],
      dtype=float32)>

In [135]:
np_array_transpose = np.transpose(np_arr_2)
np_array_transpose

array([[ 5,  1, -4],
       [ 0, -3,  0],
       [ 4,  8, -9],
       [ 5, -1, -5]])

In [136]:
torch_tensor_transpose = torch.transpose(torch_tensor_2, 0, 1)
torch_tensor_transpose

tensor([[  1,  -9,  -3],
        [  8, -10,  -7],
        [  0,  -9,  -4],
        [ -2,   0,   8]])

In [137]:
tf_tensor_transpose = tf.transpose(tf_tensor_2)
tf_tensor_transpose

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1.6345768 , -3.8236713 ,  2.0925856 ],
       [ 5.242193  , -0.25904465,  5.5088787 ],
       [ 0.43196487, -8.645498  ,  7.718027  ],
       [-4.9151683 , -3.7031531 , -7.3018003 ]], dtype=float32)>

In [138]:
np_matmul = np.matmul(np_arr_1, np_array_transpose)
np_matmul

array([[-80, -46, 128],
       [-33, -30,  67],
       [-25, -25,  42]])

In [139]:
torch_matmul = torch.matmul(torch_tensor_1, torch_tensor_transpose)
torch_matmul

tensor([[  22,   36,  -62],
        [ -89,  163,   99],
        [  87, -180, -148]])

In [140]:
tf_matmul = tf.matmul(tf_tensor_1, tf_tensor_transpose)
tf_matmul

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-36.226315, -17.063108, -62.29872 ],
       [ 21.901602,  -9.125889,  61.553036],
       [ 21.210764, -70.07383 ,  74.909744]], dtype=float32)>