In [1]:
import numpy as np 

In [2]:
arr_1 = np.array([[1, 2], [3, 4]])
arr_1 

array([[1, 2],
       [3, 4]])

In [3]:
arr_transposed_1 = np.transpose(arr_1)
arr_transposed_1

array([[1, 3],
       [2, 4]])

In [4]:
arr_transposed_2 = arr_1.T
arr_transposed_2

array([[1, 3],
       [2, 4]])

In [6]:
import tensorflow as tf 
import torch

In [8]:
def set_seed(seed: int = 2024) -> None:
    np.random.seed(seed)
    tf.random.seed(seed)
    torch.manual_seed(seed)


In [ ]:
np_arnp.array(-10, 10, (3, 4))