In [9]:
import numpy as np 

In [10]:
arr_1 = np.array([[1, 2], [3, 4]])
arr_1 

array([[1, 2],
       [3, 4]])

In [11]:
arr_transposed_1 = np.transpose(arr_1)
arr_transposed_1

array([[1, 3],
       [2, 4]])

In [12]:
arr_transposed_2 = arr_1.T
arr_transposed_2

array([[1, 3],
       [2, 4]])

In [13]:
import tensorflow as tf 
import torch

In [14]:
def set_seed(seed: int = 2024) -> None:
    np.random.seed(seed)
    tf.random.seed(seed)
    torch.manual_seed(seed)

In [15]:
np_arr_1 = np.random.randint(-10, 10, (3, 4))

In [16]:
np_arr_1

array([[ 0, -1, -4,  6],
       [-6,  0,  1, -3],
       [ 2,  0, -8, -7]])

In [17]:
torch_tensor = torch.random.randint(-10, 10, (3, 4))
torch_tensor

AttributeError: module 'torch.random' has no attribute 'randint'