In [1]:
import numpy as np 
import tensorflow as tf 
import torch

In [2]:
list_1D = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr_1D = np.array(list_1D)
arr_1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
tensor_1D_pt = torch.tensor(list_1D)
tensor_1D_pt

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
tensor_1D_tf = tf.convert_to_tensor(list_1D)
tensor_1D_tf

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [6]:
list_2D = [[1, 2, 3], 
           [4, 5, 6], 
           [7, 8, 9]]

arr_2D = np.array(list_2D)
arr_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr_2D.shape

(3, 3)

In [8]:
arr_2D.dtype

dtype('int32')

In [9]:
type(arr_2D)

numpy.ndarray

In [10]:
tensor_2D_pt = torch.tensor(arr_2D)
tensor_2D_pt

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)

In [11]:
tensor_2D_pt.shape

torch.Size([3, 3])

In [12]:
tensor_2D_pt.dtype

torch.int32

In [13]:
type(tensor_2D_pt)

torch.Tensor

In [14]:
tensor_2D_pt.device

device(type='cpu')

In [15]:
tensor_2D_tf = tf.convert_to_tensor(list_2D)
tensor_2D_tf

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [16]:
tensor_2D_tf.dtype

tf.int32

In [17]:
tensor_2D_tf.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [18]:
type(tensor_2D_tf)

tensorflow.python.framework.ops.EagerTensor