In [4]:
import numpy as np 
import torch 
import tensorflow as tf

In [8]:
list_1D = [1, 2, 3, 4, 5, 6, 7, 8, 9]

arr_1D = np.array(list_1D)
print("Mảng 1 chiều NumPy: \n", 
      arr_1D, '\n', type(arr_1D))

Mảng 1 chiều NumPy: 
 [1 2 3 4 5 6 7 8 9] 
 <class 'numpy.ndarray'>


In [10]:
tensor_1D_pt = torch.tensor(list_1D)
print("Mảng 1 chiều Torch: \n", 
      tensor_1D_pt, '\n',
      type(tensor_1D_pt))

Mảng 1 chiều Torch: 
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) 
 <class 'torch.Tensor'>


In [12]:
tensor_1D_tf = tf.convert_to_tensor(list_1D)
print("Mảng 1 chiều Tensorflow: \n", 
      tensor_1D_tf)

Mảng 1 chiều Tensorflow: 
 tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [13]:
import numpy as np

list_2D = [[1, 2, 3], 
           [4, 5, 6], 
           [7, 8, 9]]

arr_2D = np.array(list_2D)

arr_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr_2D.shape

(3, 3)

In [15]:
arr_2D.dtype

dtype('int32')

In [17]:
type(arr_2D)

numpy.ndarray

In [19]:
import torch

In [21]:
tensor_2D_pt = torch.tensor(arr_2D)
tensor_2D_pt

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)

In [22]:
tensor_2D_pt.shape

torch.Size([3, 3])

In [23]:
tensor_2D_pt.dtype

torch.int32

In [24]:
type(tensor_2D_pt)

torch.Tensor

In [25]:
tensor_2D_pt.device

device(type='cpu')

In [26]:
import tensorflow as tf 
tensor_2D_tf = tf.convert_to_tensor(list_2D)
tensor_2D_tf

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [27]:
tensor_2D_tf.shape

TensorShape([3, 3])

In [28]:
tensor_2D_tf.dtype

tf.int32

In [30]:
type(tensor_2D_tf)

tensorflow.python.framework.ops.EagerTensor

In [31]:
tensor_2D_tf.device

'/job:localhost/replica:0/task:0/device:CPU:0'